'use client';

/**
 * useProgram Hook - Anchor program connection and interaction
 */

import { useMemo } from 'react';
import { useConnection, useAnchorWallet } from '@solana/wallet-adapter-react';
import { PublicKey, Connection } from '@solana/web3.js';
import { AnchorProvider, Program, Idl } from '@coral-xyz/anchor';

// Casino program ID (placeholder - will be set after deployment)
export const CASINO_PROGRAM_ID = new PublicKey(
  process.env.NEXT_PUBLIC_CASINO_PROGRAM_ID || 'CCcasino111111111111111111111111111111111111'
);

// Minimal IDL for type safety (full IDL generated by Anchor build)
const CASINO_IDL: Idl = {
  version: '0.1.0',
  name: 'cc_casino',
  instructions: [
    {
      name: 'playCoinflip',
      accounts: [],
      args: [
        { name: 'betAmount', type: 'u64' },
        { name: 'choice', type: 'u8' },
      ],
    },
  ],
};

export interface UseProgramResult {
  program: Program | null;
  provider: AnchorProvider | null;
  connected: boolean;
  programId: PublicKey;
}

export function useProgram(): UseProgramResult {
  const { connection } = useConnection();
  const wallet = useAnchorWallet();

  const { program, provider } = useMemo(() => {
    if (!wallet) {
      return { program: null, provider: null };
    }

    const provider = new AnchorProvider(connection, wallet, {
      commitment: 'confirmed',
    });

    // Note: In production, use the full generated IDL
    const program = new Program(CASINO_IDL, CASINO_PROGRAM_ID, provider);

    return { program, provider };
  }, [connection, wallet]);

  return {
    program,
    provider,
    connected: !!wallet,
    programId: CASINO_PROGRAM_ID,
  };
}

export default useProgram;
